### ISSUE TITLE
Python Environment: Scikit learn & Numpy

### ISSUE THREAD

**Issue by RaymonHE** [coltonstearns/SpOT#5]
Hi Colton, I set up the python environment with the given setup.sh:
**_bash setup.sh /home/mars/anaconda3 spot_env_**

However, the environment is not properly installed:
**How to solve the problems about the numpy and the scikit-learn?**
![2024-01-30 19-57-27](https://github.com/coltonstearns/SpOT/assets/49650511/6dc11303-d493-4527-86d6-44f31b970ccc)

**Comment by coltonstearns** [comment]
Yes, pip will report version mismatches, but these reported version mismatches are stricter than actually necessary, and the code does need these exact version to run.

**Comment by RaymonHE** [comment]
Hi Colton, I decided to create a new environment with your updated setup.sh.
**_### My CUDA is 11.7. Will this cause a problem when installing the environment?_**  
I created a virtual conda environment with python3.8.
After When I typed this line into the terminal, 
**yes | pip install numpy**
Something went wrong. I don't know if you encountered the same problem as I did. It seems like there is something wrong with the tensorboard, but there is no information about the required tensorflow of tensorboard in the setup.py. So I wonder how to fix this problem. 
![2024-02-01 10-36-36屏幕截图](https://github.com/coltonstearns/SpOT/assets/49650511/4e8d2ffa-9b3c-424d-81b7-fd7f2294876b)

**Comment by RaymonHE** [comment]
> Hi Colton, I decided to create a new environment with your updated setup.sh. My CUDA is 11.7. Will this cause a problem when installing the environment? I created a virtual conda environment with python3.8. After When I typed this line into the terminal, **yes | pip install numpy** Something went wrong. I don't know if you encountered the same problem as I did. It seems like there is something wrong with the tensorboard, but there is no information about the required tensorflow of tensorboard in the setup.py. So I wonder how to fix this problem. ![2024-02-01 10-36-36屏幕截图](https://private-user-images.githubusercontent.com/49650511/301367785-4e8d2ffa-9b3c-424d-81b7-fd7f2294876b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY3NTUzMTYsIm5iZiI6MTcwNjc1NTAxNiwicGF0aCI6Ii80OTY1MDUxMS8zMDEzNjc3ODUtNGU4ZDJmZmEtOWIzYy00MjRkLTgxYjctZmQ3ZjIyOTQ4NzZiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjAxVDAyMzY1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTViMzU3MGYzYmIyZDMzZWJjNTczY2MwMzg3Y2FmZTY1YWEzMDZlMjc4NmU3MTk0YTNlYTUyMzVkMjAwNWM4OGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.AVFv21v4hmL-qPYep3m-iF5Pp3NdyIK2djbwXDIlvDw)

I solve this problem by installing the latest version of these python packages.

**pip install google-auth
pip install requests-oauthlib
pip install grpcio
pip install Markdown
pip install Werkzeug**
![2024-02-01 10-43-07屏幕截图](https://github.com/coltonstearns/SpOT/assets/49650511/4bdd50b3-4983-4b20-9a45-ebb8ffaa66d5)

**Comment by RaymonHE** [comment]
Now in the 32 line of the setup/sh file(I succeeded in implementing all installation before), when i typed in
pip install .
The wheels of pytorch3d can not be build successfully. I wonder how to fix this problem. It seems like I need to install another python package concerning with pytorch.
![2024-02-01 11-37-47屏幕截图](https://github.com/coltonstearns/SpOT/assets/49650511/dba8b412-b9de-4625-b05e-82edb60058aa)

**Comment by coltonstearns** [comment]
Which package failed to compile (the above output shows that there was a failure, but there should be a specific package error above). Building this worked on my machine... You can also try checking out slightly different versions of pytorch3D - however I know that 0.7+ doesn't work with the environment.

**Comment by RaymonHE** [comment]
Yes, Colton. I have tried  v0.7.0   v0.7.1   v0.7.2   v0.7.3   v0.7.4   v0.7.5, but they all failed in compeiling.
And i also tested on 0.6+(v0.6     v0.6.0   v0.6.1   v0.6.2 ), but they are also unfeasible. And  i will try the rest of them tmr.
As you can see the error information in the terminal  below, which is the same as the output when i was trying to install 0.6.2 as descriped in the setup.py
![2024-02-02 23-40-25屏幕截图](https://github.com/coltonstearns/SpOT/assets/49650511/89e03a9d-a0ad-4787-914e-5004829b9267)

I wonder if it's because of my version of cuda, since my cuda version is 11.7, however , yours is 11.1, is this the reason why the environment setting fails? since in the terminal , when i check out the version of the pytorch3d, it shows like this,

**_### Head is now located in the d049cd2 PyTorch 1.10 + CUDA 11.1 builds_**

Sorry for the Chinese setting, i will adjust it later for your convenience to see, but i think i should upload the screen on it for you to check the problem.
![2024-02-02 23-47-44屏幕截图](https://github.com/coltonstearns/SpOT/assets/49650511/ee06c2a5-26ee-457b-a9c5-cd7d56ef70c3)

**Comment by RaymonHE** [comment]
Hi Colton, I created an environment in the docker. I can share that.
